config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users do
    resources :albums do
      resources :photos
    end
  end
  # root 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :photos,  dependent: :destroy
  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
  validate :max_photos, on: [:create, :update]

  def max_photos
    if self.photos.length > 25
      self.errors.add(:base, "please upload less than 25 photos")
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  validates :tagline, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :authenticate_user!

	def index
		@albums = current_user.albums
	end

	def new
	  @album = current_user.albums.new
	end

	def create
	  @album = current_user.albums.new(album_params)
	  @album.save
    if @album.save
  	  redirect_to user_album_path(current_user, @album)
    else
      render 'new'
    end
	end

	def show
    @album = Album.find(params[:id])
  end

	def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to user_albums_path(current_user)
	end

  private
    def album_params
      params.require(:album).permit(:name, photos_attributes: [:id, :image, :tagline,  :_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@photos = Photo.all.includes(album: :user).last(25).reverse
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_photo_fields.html.erb
<div class='nested-fields'>
    <%= f.text_field :tagline, :required => true %>
    <%= f.file_field :image, :required => true %>
    <%= link_to_remove_association "remove photo", f %>
</div>
<br>

app/views/albums/index.html.erb
<%= link_to 'Create Album', new_user_album_path(current_user), class: "btn btn-info" %>
<br><hr>
<% unless @albums.blank? %> 
<h5>Listing Albums</h5>
  <table class="table table-striped">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Show</th>
      <th>Delete</th>
    </tr>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.id %></td>
        <td><%= album.name %></td>
        <td><%= link_to 'show', user_album_path(current_user, album) %></td>
        <td><%= link_to 'delete', user_album_path(current_user, album),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h5>No photos available!!</h5>
<% end %> 

app/views/albums/new.html.erb
<h2>Add a album:</h2>
<%= form_with(model: [ current_user, current_user.albums.build ], local: true) do |form| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, "error") %> prohibited
        this album from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, :required => true %>
  </p>
  <p>

  <h3>Photos</h3>
  <div id='albums'>
    <%= form.fields_for :photos do |photo| %>
      <%= render 'photo_fields', :form => photo %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add photos', form, :photos %>
    </div>
  </div>
    <%= form.submit %>
  </p>
<% end %>
 

app/views/albums/show.html.erb
<h5> Album: <%= @album.name %> </h5>
<hr>
<% unless @album.photos.blank? %>
  <h1>Album Photos</h1>
  <table class="table table-striped">
    <tr>
      <th>Id</th>
      <th>Image</th>
      <th>Tagline</th>
      <th>Owner</th>
      <th>Created at</th>
    </tr>
   
    <% @album.photos.each do |photo| %>
      <tr>
        <td><%= photo.id %></td>
        <td><%= image_tag photo.image(:thumb) %></td>
        <td><%= photo.tagline %></td>
        <td><%= current_user.username %></td>
        <td><%= photo.created_at.strftime("%d-%m-%Y") %></td>
      </tr>
    <% end %>
  </table>

<% else %>
  <h5>No photos available!!</h5>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbumApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text pull-left"></p>
    <p class="navbar-text pull-right"><%= link_to 'Home', root_path, :class => 'navbar-link' %> | </p>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %> |</strong>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "My Albums", user_albums_path(current_user), method: :get, :class => 'navbar-link'  %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 
       
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<% unless @photos.blank? %> 
  <h5>Gallary Photos</h5>
  <table class="table table-striped">
    <tr>
      <th>Sr.No</th>
      <th>Image</th>
      <th>Owner</th>
    </tr>
   
    <% @photos.each_with_index do |photo, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= image_tag photo.image(:thumb) %></td>
        <td><%= photo.album.user.username %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h5>No photos available!!</h5>
<% end %> 